package com.estebancoloradogonzalez.tension.ui.navigation

object NavigationRoutes {
    const val REGISTER = "register"
    const val HOME = "home"
    const val PROFILE = "profile"
    const val WEIGHT_HISTORY = "weight-history"
    const val SETTINGS = "settings"
    const val EXERCISE_DICTIONARY = "exercise-dictionary"
    const val EXERCISE_DETAIL = "exercise-detail/{exerciseId}"
    const val CREATE_EXERCISE = "create-exercise"
    const val TRAINING_PLAN = "training-plan"
    const val PLAN_VERSION_DETAIL = "plan-version-detail/{moduleVersionId}"
    const val EXERCISE_HISTORY = "exercise-history/{exerciseId}"
    const val SESSION_HISTORY = "session-history"
    const val SESSION_DETAIL = "session-detail/{sessionId}"
    const val METRICS = "metrics"
    const val MUSCLE_VOLUME = "muscle-volume"
    const val PROGRESSION_TREND = "progression-trend"
    const val ACTIVE_SESSION = "active-session/{sessionId}"
    const val REGISTER_SET = "register-set/{sessionExerciseId}"
    const val SUBSTITUTE_EXERCISE = "substitute-exercise/{sessionExerciseId}"
    const val SESSION_SUMMARY = "session-summary/{sessionId}"
    const val DELOAD_MANAGEMENT = "deload"
    const val ALERT_CENTER = "alert-center"
    const val ALERT_DETAIL = "alert-detail/{alertId}"
    const val EXPORT_BACKUP = "export-backup"
    const val IMPORT_BACKUP = "import-backup"

    fun exerciseDetailRoute(exerciseId: Long) = "exercise-detail/$exerciseId"
    fun exerciseHistoryRoute(exerciseId: Long) = "exercise-history/$exerciseId"
    fun planVersionDetailRoute(moduleVersionId: Long) = "plan-version-detail/$moduleVersionId"
    fun activeSessionRoute(sessionId: Long) = "active-session/$sessionId"
    fun registerSetRoute(sessionExerciseId: Long) = "register-set/$sessionExerciseId"
    fun substituteExerciseRoute(sessionExerciseId: Long) = "substitute-exercise/$sessionExerciseId"
    fun sessionSummaryRoute(sessionId: Long) = "session-summary/$sessionId"
    fun sessionDetailRoute(sessionId: Long) = "session-detail/$sessionId"
    fun alertDetailRoute(alertId: Long) = "alert-detail/$alertId"
}
