package com.estebancoloradogonzalez.tension.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme — M3 Roles (seed: #8B1A1A)
val md_theme_light_primary = Color(0xFF8B1A1A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF5DDDD)
val md_theme_light_onPrimaryContainer = Color(0xFF5C0E0E)
val md_theme_light_secondary = Color(0xFF6B4F4F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF0E0E0)
val md_theme_light_onSecondaryContainer = Color(0xFF4A3333)
val md_theme_light_tertiary = Color(0xFF5C6B4F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE0EEDD)
val md_theme_light_onTertiaryContainer = Color(0xFF334A29)
val md_theme_light_background = Color(0xFFFFF8F0)
val md_theme_light_onBackground = Color(0xFF1C1B1B)
val md_theme_light_surface = Color(0xFFFFF8F0)
val md_theme_light_onSurface = Color(0xFF1C1B1B)
val md_theme_light_surfaceVariant = Color(0xFFF5E6D8)
val md_theme_light_onSurfaceVariant = Color(0xFF524340)
val md_theme_light_outline = Color(0xFF857370)
val md_theme_light_outlineVariant = Color(0xFFD8C2BD)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFFEF1E6)
val md_theme_light_surfaceContainer = Color(0xFFF8EBE0)
val md_theme_light_surfaceContainerHigh = Color(0xFFF2E5DA)
val md_theme_light_surfaceContainerHighest = Color(0xFFEDE0D5)
val md_theme_light_inverseSurface = Color(0xFF322F2E)
val md_theme_light_inverseOnSurface = Color(0xFFFBF0EB)

// Dark Theme — M3 Roles
val md_theme_dark_primary = Color(0xFFFFB4AB)
val md_theme_dark_onPrimary = Color(0xFF690005)
val md_theme_dark_primaryContainer = Color(0xFF6E1010)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_secondary = Color(0xFFE0C0C0)
val md_theme_dark_onSecondary = Color(0xFF3E2828)
val md_theme_dark_secondaryContainer = Color(0xFF523A3A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF0E0E0)
val md_theme_dark_tertiary = Color(0xFFC0D4B0)
val md_theme_dark_onTertiary = Color(0xFF2A3A20)
val md_theme_dark_tertiaryContainer = Color(0xFF425238)
val md_theme_dark_onTertiaryContainer = Color(0xFFE0EEDD)
val md_theme_dark_background = Color(0xFF1C1B1B)
val md_theme_dark_onBackground = Color(0xFFE8E0DC)
val md_theme_dark_surface = Color(0xFF1C1B1B)
val md_theme_dark_onSurface = Color(0xFFE8E0DC)
val md_theme_dark_surfaceVariant = Color(0xFF524340)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BD)
val md_theme_dark_outline = Color(0xFFA08C88)
val md_theme_dark_outlineVariant = Color(0xFF524340)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF930009)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_surfaceContainerLowest = Color(0xFF141313)
val md_theme_dark_surfaceContainerLow = Color(0xFF1C1B1B)
val md_theme_dark_surfaceContainer = Color(0xFF252322)
val md_theme_dark_surfaceContainerHigh = Color(0xFF302E2D)
val md_theme_dark_surfaceContainerHighest = Color(0xFF3B3937)
val md_theme_dark_inverseSurface = Color(0xFFE8E0DC)
val md_theme_dark_inverseOnSurface = Color(0xFF322F2E)

// Semantic Domain Colors — Progression Signals (RNF05)
val ProgressionPositiveLight = Color(0xFF2E7D32)
val ProgressionPositiveDark = Color(0xFF81C784)
val MaintenanceLight = Color(0xFF8D6E00)
val MaintenanceDark = Color(0xFFFFD54F)
val RegressionLight = Color(0xFFC62828)
val RegressionDark = Color(0xFFEF9A9A)

// Semantic Domain Colors — Exercise States in Session (E1)
val ExerciseNotStartedLight = Color(0xFF857370)
val ExerciseNotStartedDark = Color(0xFFA08C88)
val ExerciseInExecutionLight = Color(0xFF1565C0)
val ExerciseInExecutionDark = Color(0xFF64B5F6)
val ExerciseCompletedLight = Color(0xFF2E7D32)
val ExerciseCompletedDark = Color(0xFF81C784)
val ExerciseRowInExecutionBgLight = Color(0xFFE3F2FD)
val ExerciseRowInExecutionBgDark = Color(0xFF1A2733)
val ExerciseRowCompletedBgLight = Color(0xFFE8F5E9)
val ExerciseRowCompletedBgDark = Color(0xFF1A2E1A)

// Semantic Domain Colors — Alert Levels (H1, H2)
val AlertCrisisLight = Color(0xFFC62828)
val AlertCrisisDark = Color(0xFFEF9A9A)
val AlertCrisisBgLight = Color(0xFFFFDAD6)
val AlertCrisisBgDark = Color(0xFF930009)
val AlertHighLight = Color(0xFFE65100)
val AlertHighDark = Color(0xFFFFB74D)
val AlertHighBgLight = Color(0xFFFFF3E0)
val AlertHighBgDark = Color(0xFF4E2600)
val AlertMediumLight = Color(0xFF8D6E00)
val AlertMediumDark = Color(0xFFFFD54F)
val AlertMediumBgLight = Color(0xFFFFF8E1)
val AlertMediumBgDark = Color(0xFF4A3800)

// Semantic Domain Colors — Trends (G3)
val TrendAscendingLight = Color(0xFF2E7D32)
val TrendAscendingDark = Color(0xFF81C784)
val TrendStableLight = Color(0xFF8D6E00)
val TrendStableDark = Color(0xFFFFD54F)
val TrendDecliningLight = Color(0xFFC62828)
val TrendDecliningDark = Color(0xFFEF9A9A)

// Semantic Domain Colors — Session Status (E5, F1, F2)
val SessionCompletedLight = Color(0xFF2E7D32)
val SessionCompletedDark = Color(0xFF81C784)
val SessionIncompleteLight = Color(0xFFE65100)
val SessionIncompleteDark = Color(0xFFFFB74D)

// Semantic Domain Colors — Deload (B1, E1, I1)
val DeloadActiveLight = Color(0xFF1565C0)
val DeloadActiveDark = Color(0xFF64B5F6)